name: Maven Test Compilation

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to main

jobs:
  compile-tests:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches the code from the repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin JDK
          java-version: '17'  # Change to 11 or 8 if needed
          cache: maven  # Caches dependencies to speed up builds

      - name: Run Maven Test Compilation
        run: mvn test-compile  # Compiles ONLY test Java files (src/test/java)